name: Tests

on: [ push ]

env:
  GO_VERSION: 1.21.6

jobs:
  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        run: go build -v ./...
      - name: Run integration tests
        run: go test -json ./test/integration > IntegrationTestResults-${{ env.GO_VERSION }}.json
      - name: Upload Go integration tests results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ env.GO_VERSION }}
          path: IntegrationTestResults-${{ env.GO_VERSION }}.json
